# Generated by Django 2.2.5 on 2019-09-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_size',
            field=models.IntegerField(blank=True),
        ),
    ]
