# Generated by Django 2.2.5 on 2019-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190922_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='estimated_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='estimated_rent_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='estimated_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='estimated_sale_price_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='tax_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='tax_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
